Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "amaretto")
Ingredient.create(name: "rhum")
Ingredient.create(name: "gin")
Ingredient.create(name: "tonic water")
Ingredient.create(name: "sugar")
Ingredient.create(name: "whisky")
Ingredient.create(name: "vodka")
Ingredient.create(name: "ginger beer")
Ingredient.create(name: "angustura")
Ingredient.create(name: "passion fruit")
Ingredient.create(name: "cucumber")
Ingredient.create(name: "lime")
Ingredient.create(name: "cramberry")
Ingredient.create(name: "mezcal")
Ingredient.create(name: "triple sec")
Ingredient.create(name: "champagne")
Ingredient.create(name: "bitters")
Ingredient.create(name: "cognac")
Ingredient.create(name: "egg")
Ingredient.create(name: "spiced rhum")
Ingredient.create(name: "bourbon")
Ingredient.create(name: "aperol")
Ingredient.create(name: "campari")
Ingredient.create(name: "vermouth")
Ingredient.create(name: "martini")
Ingredient.create(name: "proseco")
Ingredient.create(name: "orange")
